# To celebrate the end of your first week: a long warmup!

# Part 1: Numpy practice

(If you get stuck at one part, try the other part)

Run the cell below to load the machinery for testing your work, and then 

- import the numpy library with the alias 'np'

In [1]:
#Run this cell without changes

from test_background import test_dict, run_test

In [2]:
#Your code here
import numpy as np

Create a variable called x that is a list of 100 0s

In [39]:
#Your code here

x = np.zeros(100)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#test by running this cell

run_test(x, 'x1')

'Hey, you did it.  Good job.'

Find another way to create a list of 100 0s; assign it to a new variable called y

In [7]:
#Your code here
y = [0] * 100

In [8]:
#test by running this cell

run_test(y, 'y1')

'Hey, you did it.  Good job.'

Turn x and y into numpy arrays

In [9]:
#Your code here
y = np.array(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
#run this cell to test yer x

run_test(x, 'x2')

'Hey, you did it.  Good job.'

In [11]:
#run this cell to test yer y

run_test(y, 'y2')

'Hey, you did it.  Good job.'

In both x and y, insert all of the first 100 [positive integers](https://mathworld.wolfram.com/PositiveInteger.html) in-between the 0s

With x, start inserting at index 0

With y, start at index 1

*Hint: couple ways to do this, but [here's one](https://numpy.org/doc/1.18/reference/generated/numpy.insert.html)*

In [40]:
#Your code here
np.insert(x, range(1, 101), [range(1, 101)])

np.insert(y, range(1, 101), [range(1, 101)])
# np.insert(a, [1], [[1],[2],[3]], axis=1)
# array([[1, 1, 1],
#        [2, 2, 2],
#        [3, 3, 3]])

array([  0,   1,   0,   2,   0,   3,   0,   4,   0,   5,   0,   6,   0,
         7,   0,   8,   0,   9,   0,  10,   0,  11,   0,  12,   0,  13,
         0,  14,   0,  15,   0,  16,   0,  17,   0,  18,   0,  19,   0,
        20,   0,  21,   0,  22,   0,  23,   0,  24,   0,  25,   0,  26,
         0,  27,   0,  28,   0,  29,   0,  30,   0,  31,   0,  32,   0,
        33,   0,  34,   0,  35,   0,  36,   0,  37,   0,  38,   0,  39,
         0,  40,   0,  41,   0,  42,   0,  43,   0,  44,   0,  45,   0,
        46,   0,  47,   0,  48,   0,  49,   0,  50,   0,  51,   0,  52,
         0,  53,   0,  54,   0,  55,   0,  56,   0,  57,   0,  58,   0,
        59,   0,  60,   0,  61,   0,  62,   0,  63,   0,  64,   0,  65,
         0,  66,   0,  67,   0,  68,   0,  69,   0,  70,   0,  71,   0,
        72,   0,  73,   0,  74,   0,  75,   0,  76,   0,  77,   0,  78,
         0,  79,   0,  80,   0,  81,   0,  82,   0,  83,   0,  84,   0,
        85,   0,  86,   0,  87,   0,  88,   0,  89,   0,  90,   

In [34]:
#run this cell to test yer x

run_test(x, 'x3')

'Try again'

In [35]:
#run this cell to test yer y

run_test(y, 'y3')

'Try again'

Remove all the 0s from both x and y

Use different methods of removal for x and y

In [43]:
#Your code here
x = np.delete(x, 0)
x

y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
#run this cell to test yer x

run_test(x, 'x4')

'Try again'

In [199]:
#run this cell to test yer y

run_test(y, 'y4')

# Part 2: Estimating pi (with viz!)

(This is a little bit more math-y than the content we've covered so far)

First import pyplot from matplotlib under the alias plt

Also, run the command `%matplotlib inline` so that jupyter renders the plots inside the notebook

In [45]:
#Your code here
from matplotlib import pyplot as plt
%matplotlib inline

Picture a circle perfectly circumscribed inside a unit square

or just look at the viz below

![](viz/unit_square.png)

#### Math refresher

The area of the unit square is 1

The radius of the circle is $\frac{1}{2}$, and the area of the circle is $\pi \times (\frac{1}{2})^2 = \frac{\pi}{4}$

If we randomly throw points inside the square: 

$ \lim \limits_{points \to \infty} ($area covered by all points$) = 1 $

and

$ \lim \limits_{{points} \to \infty} ($area covered by points in circle$) = \frac{\pi}{4} $

So, if we randomly throw *a finite number* of points in the square,

$$\frac{\#ofCircle Points}{\#ofTotal Points} \approx \frac{\pi}{4}$$

and

$$ 4 \times \frac{\#ofCircle Points}{\#ofTotal Points} \approx \pi $$

#### Look just tell me what we're doing here

We're going to create a plot that, inside of a unit square whose lower-left corner is at (0,0):
- plots 1000 random points
- colors them differently if they're inside or outside an inscribed circle

Then, we'll calculate our estimate for pi 

Two s t r e t c h goals:
- calculate the error of the estimate
- turn our work into a function that can recreate what we've done with an arbitrary number of points

#### Let's graph

First we're going to create the points to throw inside the square.

- Use numpy to create a variable `x` that has 1000 randomly drawn floats (a numerical data type which has decimals, as opposed to `integers` which don't) between 0 and 1.

- Use numpy to creat another variable `y` that has a different set of 1000 randomly-drawn floats b/t 0 and 1.

These are the x and y coordinates for the random points we'll throw at the square and inscribed circle

- Also, run `np.random.seed(33)` at the top of the cell

This "seeds" the pseudorandom number generator to produce the same numbers each time the variables are instantiated

[*Hint*](https://numpy.org/devdocs/reference/random/generated/numpy.random.random.html?highlight=random%20random#numpy.random.random)

In [54]:
#Your code here
np.random.seed(33)
x = np.random.random(1000)
y = np.random.random(1000)
type(x)

numpy.ndarray

In [52]:
#run this cell to check yer x

run_test(x, 'x5')

'Hey, you did it.  Good job.'

In [53]:
#run this cell to check yer y

run_test(y, 'y5')

'Hey, you did it.  Good job.'

The x and y coordinates of the points inside the circle are 
$$ (x^2 + y^2)<=\frac{1}{2} $$

Select all the points in x inside the circle and assign them to the variable inside_x

Do the same thing for the points in y, and assign them to the variable inside_y


*Hint 1: For 1D arrays, addition and multiplication operates element by element.  Boolean selection of a 1D array also operates element by element.* 

*Eg if `ex1 = np.array([1,2,3])` and `ex2 = np.array([5,6,7])`*, 


`ex1[ex1*5+ex2*10<80]`

= 

"at each index value, 

if (the value of ex1 at that index)*5 +

(the value of ex2 at that index)*10 < 80,

include the value of ex1 at that index" 

= 

`[1,2]`


*Hint 2: the formula for a circle centered at (h,k) with radius r is* 
    $$(x-h)^2 + (y-k)^2 = r^2$$
*Where is the center of a circle inscribed in a unit square whose lower-left corner is at (0,0)?  Are points inside the circle greater than or less than $r^2$?*

In [67]:
#Your code here
import math

circle_points = (x-1/2)**2 + (y - 1/2)**2
inside_arr = circle_points[circle_points < 1/4]
inside_arr
# inside_x = x < (1/4 - (y-1/2)**2)**(1/2) + 1/2

array([ True,  True,  True, False,  True,  True, False, False,  True,
        True, False,  True, False,  True,  True, False, False,  True,
        True,  True,  True,  True,  True, False,  True, False, False,
       False,  True,  True, False, False,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
       False, False,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,

In [65]:
#run this cell to check inside_x

run_test(inside_x, 'inside_x')

'Try again'

In [197]:
#run this cell to check inside_y

run_test(inside_y, 'inside_y')

Do the same thing for the points that lie within the square but outside the circle

Ie, select all the points in x and y that satisfy the condition
$$ (x^2 + y^2)>\frac{1}{2} $$
assign them to the variables outside_x and outside_y, respectively

In [176]:
#Your code here

In [196]:
# #run this cell to check outside_x

run_test(outside_x, 'outside_x')

In [195]:
#run this cell to check outside_y

run_test(outside_y, 'outside_y')

Now, create a scatter plot of the "inside circle" points.  Color them blue, with alpha=.8 and edgecolor=None.

Create another scatter plot of the "outside circle" points.  Color them red, same alpha / edgecolor as above.

Plot both scatter plots in the same graph.

Call the title of the graph "Random Points Distributed across Inscribed Circle in Unit Square to Estimate Pi".  

In [182]:
#Your code here

You should produce a figure like the one below (which has a figsize(20,10) and used ax.set_aspect('equal'), fyi)

![](viz/delicious_pi.png)

#### Calculate Estimate

Now, calculate your $\pi$ estimate

Create the following variables:
- the number of pts inside the circle
    - name this variable pts_in_circle
    
    
- the number of pts outside the circle
    - name this variable pts_out_circle
    
    
- an estimate for $\pi$ that uses pts_in_circle and pts_out_circle
    - name this variable pi_est

**S t r e t c h goal 1**
    
- a calculation of the pct error of pi_est 
    - name this variable pi_est_error_pct
    
Print a sentence using the above variables that includes the estimate of pi and how many points it's based on 

(and the error, if you get that far)

In [184]:
#Your code here

In [194]:
#run this cell to test pts_in_circle, pts_out_circle, pi_est

[
    print(pair[1]+f'? {run_test(pair[0], pair[1])}')
    for pair in 
    zip(objects, obj_names)
]
print()

In [193]:
#run this cell to test pct error

run_test(pi_est_error_pct, 'pi_est_error_pct')

In [192]:
#run this cell to test rounded pct error

run_test(pi_est_error_pct_rounded, 'pi_est_error_pct_rounded')

**S t r e t c h goal 2**


Turn your work into a function that:

- can take as a parameter an arbitrary number of points to estimate pi

- prints a graph like the one above

- returns {'pi_estimate': pi_est, 'est_error_pct': pi_est_error_pct} 